spring:
  application:
    name: "back-end"
  datasource:
    url: jdbc:postgresql://localhost:5432/appresence
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    whitelabel:
      enabled: false